Add ability to upgrade in debian pkg scripts. (Closes: #811162)

diff --git a/debian/dms-core.postinst b/debian/dms-core.postinst
--- a/debian/dms-core.postinst
+++ b/debian/dms-core.postinst
@@ -17,9 +17,6 @@ set -e
 # for details, see http://www.debian.org/doc/debian-policy/ or
 # the debian-policy package
 
-PGVER="9.3"
-DMSPGCONFDIR="/etc/postgresql/$PGVER/dms"
-
 case "$1" in
     configure)
 	# Add users and groups
@@ -74,9 +71,8 @@ case "$1" in
 
 	# Set up kernel SHM
 	service procps reload
-	# Create PG dms cluster
-	if [ ! -d /etc/postgresql/${PGVER}/dms ] \
-		|| [ -z "$(ls ${DMSPGCONFDIR}/postgresql.conf 2>/dev/null)" ]; then
+	if ! pg_lsclusters -h | perl -pe 's/^\S+\s+(\S+)\s+.*$/\1/' | grep -q dms; then
+		# Create PG dms cluster
 		dms_createdb || {
 		        echo "Error: could not create dms cluster. Please create it manually with
 
@@ -84,8 +80,20 @@ case "$1" in
 
 using the -f switch if required.";
 		} >&2
+	else
+		# Upgrade PG dms cluster
+		dms_upgradedb -f || {
+		        echo "Error: could not upgrade dms cluster. Please upgrade it manually with
+
+			  dms_upgradedb
+
+";
+		} >&2
+			
 	fi
 	# Revert cluster settings of removal
+	PGVER=`pg_lsclusters -h | perl -pe 's/^(\S+\s+\S+)\s+.*$/\1/' | grep dms | perl -pe 's/^(\S+)\s+.*$/\1/'`
+	DMSPGCONFDIR="/etc/postgresql/$PGVER/dms"
 	if grep -q ^manual ${DMSPGCONFDIR}/start.conf; then
 	    perl -pe 's~^manual~auto~' -i ${DMSPGCONFDIR}/start.conf
 	    pg_ctlcluster $PGVER dms start
